---
kind: pipeline
type: docker
name: discord-bot-version
steps:
  
  - name: test
    image: rust:1.65
    commands:
      - cargo test
    when:
      branch:
        - main 
  
  - name: build
    image: rust:1.65
    commands:
      - cargo build --release
    when:
      event:
        - tag
  
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github
      files: /drone/src/target/release/discord-bot-version
      checksum:
        - sha512
    when:
      event:
        - tag
