---
kind: pipeline
type: docker
name: discord-bot-version
steps:
  
  - name: test
    image: rust:1.65
    commands:
      - cargo test
      - cargo build --release
  
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github
      files: bin/*
      checksum:
        - sha512
      when:
        event: tag
trigger:
  branch:
  - main
